config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_out: 'logout',
    password: 'secret', confirmation: 'verification',
    registration: 'register', edit: 'edit/profile'
  }, sign_out_via: [:get, :post]

  resources :groups, path: 'categories', only: [:new, :create, :index, :show, :destroy, :edit] do
    resources :expenses, only: [:new, :create, :index, :show, :destroy]
  end
  root to: "splash#index"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses

  validates :name, :icon, :user_id, presence: true

  validates :name, length: { minimum: 3, maximum: 70 }
  validates :icon, length: { minimum: 3, maximum: 5_000 }
  validates :icon, format: { with: /\A#{URI::DEFAULT_PARSER.make_regexp(%w[http https data])}\z/,
                             message: 'must be a valid URL' }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = current_user.groups
    @group_totals = @groups.to_h { |group| [group.id, group.expenses.sum(:amount)] }
  end

  def show
    @group = current_user.groups.find(params[:id])
    @expenses = @group.expenses.order(created_at: :desc)
    @total_amount = @expenses.sum(:amount)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = current_user.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "Category name", required: true %>
  </div>

  <div class="field">
    <%= form.text_field :icon, placeholder: "Icon url", required: true %>
  </div>

  <div class="actions">
    <%= form.submit "Save" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="group-item">
  <div class="img-item">
   <img src="<%= group.icon %>" alt="<%= group.name %>" >
  </div>
  <div class="details">
    <div class="inner-details">
      <h4 class="smallest-headingg">
        <%= group.name %>
      </h4>
      <p>
        <%= group.created_at.strftime('%d %b %y') %>
      </p>
    </div>
    <div class="outer-details">
      <% if action_name == 'index' %>
        <p>$<%= @group_totals&.[](group.id)%>.00</p>
      <% elsif action_name == 'show' %>
        <p>Total amount: $<%= group.expenses.sum(:amount) %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<section class="edit-category">

<div class="nav">
<h5>Edit Category</h5>
</div>

<%= render "form", group: @group %>

<%= link_to "", @group, class: 'back' %>

</section>

app/views/groups/index.html.erb
<section class="categories">
  <div class="nav">
  <p class="back-home"></p>
    <h5>categories</h5>
    <% if current_user %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'actions' %>
  <% end %>
  </div>

  <p style="color: green", class="notice"><%= notice %></p>

  <ul id="groups">
    <% @groups.each do |group| %>
      <li class="group-category">
        <%= link_to group_path(group), id: "link-group" do %>
          <%= render group %>
        <% end %>
      </li>
    <% end %>
  </ul>
    <%= link_to new_group_path, class: "new-category"  do %> 
      <p class="add">Add Category</p>
    <% end %>

</section>

app/views/groups/new.html.erb
<section class="add-category">

<div class="nav">
<h5>Add Category</h5>
</div>

<%= render "form", group: @group %>

<%= link_to "", groups_path, class: 'back' %>

</section>

app/views/groups/show.html.erb
<section class="single-category">
<div class="nav expense">
<h5> Category | Expenses</h5>
  <%= button_to "Delete Category", @group, method: :delete, class: 'actions delete' %>
  <%= link_to "Edit Category", edit_group_path(@group), class: 'actions edit'%>
</div>

<p style="color: green", class="notice other"><%= notice %></p>

<%= link_to "", groups_path, class: 'back' %>


<%= render @group %>


<div class="expenses-list">
<% if @group.expenses.any? %>
<h4>Expenses</h4>
<table>
<thead>
<tr>
<th>Name</th>
<th>Amount</th>
<th>Date</th>
<th>Action</th>
</tr>
</thead>
        <tbody>
        <% @group.expenses.order(created_at: :desc).each do |expense| %>
          <tr>
          <td><%= expense.name %></td>
          <td class="amount">$<%= expense.amount %></td>
          <td><%= expense.created_at.strftime('%B %d, %Y') %></td>
          <td>
              <div class="action">
                  <%= link_to "View", group_expense_path(@group, expense), class: "table-view"  %>
                  <%= button_to "Delete", [@group, expense], method: :delete, data: { confirm: 'Are you sure?' }, class: "table-delete"  %>
              </div>
            </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
  
  <%= link_to new_group_expense_path(@group), class: "new-expense" do %>
    <p class="add">Add expense</p>
  <% end %>

  </section>
  