config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_out: 'logout',
    password: 'secret', confirmation: 'verification',
    registration: 'register', edit: 'edit/profile'
  }, sign_out_via: [:get, :post]

  resources :groups, path: 'categories', only: [:new, :create, :index, :show, :destroy, :edit] do
    resources :expenses, only: [:new, :create, :index, :show, :destroy]
  end
  root to: "splash#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :expenses, foreign_key: 'author_id', dependent: :destroy
  has_many :groups, foreign_key: 'user_id', dependent: :destroy

  validates :name, :role, :email, :password, presence: true

  validates :name, length: { minimum: 3, maximum: 60 }
  validates :email, length: { minimum: 6, maximum: 100 }
  validates :password, length: { minimum: 6, maximum: 50 }

  def admin?
    role == 'admin'
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_group, only: %i[new create edit update destroy]
  before_action :set_expense, only: %i[edit update destroy]

  def index
    @expenses = Expense.all
  end

  def show
    @expense = Expense.find(params[:id])
    @group = Group.find(params[:group_id])
  end

  def new
    @group = Group.find(params[:group_id])
    @expense = Expense.new
  end

  def edit
    @group = Group.find(params[:group_id])
  end

  def create
    # @expense = Expense.new(expense_params)
    @expense = Expense.new(expense_params)
    @expense.author_id = current_user.id
    @expense.groups = Group.where(id: params[:expense][:group_ids]).includes([:user])

    respond_to do |format|
      if @expense.save
        format.html do
          redirect_to group_path(id: params[:expense][:group_ids].last), notice: 'Expense was successfully created.'
        end
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to group_path(@group), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to group_path(@group), notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_expense
    @expense = Expense.find(params[:id])
    @group = @expense.groups.first
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, group_ids: [])
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>">
  <p>
    <strong>Name:</strong>
    <%= expense.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    $<%= expense.amount %>
  </p>

  <p>
    <strong>Category: </strong>
    <%=  @group.name %>
  </p>

  <p>
  <strong>Created:</strong>
  <%= expense.created_at.strftime('%B %d, %Y') %>
  </p>
  
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, url: group_expenses_path(@group)) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, required: true, placeholder: "Expense name"  %>
  </div>

  <div class="field">
    <%= form.number_field :amount, required: true, placeholder: "Amount" %>
  </div>


  <div class="actions">
    <%= form.submit "Save" %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>

<%= link_to "Back to group",group_path(@group)  %>
</div>

app/views/expenses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Expenses</h1>

<div id="expenses">
  <% @expenses.each do |expense| %>
    <%= render expense %>
    <p>
      <%= link_to "Show this expense", expense %>
    </p>
  <% end %>
</div>

<%= link_to "New expense", new_expense_path %>

app/views/expenses/new.html.erb
<section class="add-expense">
  <div class="nav">
    <h5>Add Expense</h5>
  </div>

  <%= form_with(model: [@group, @expense], url: group_expenses_path(@group)) do |form| %>
    <% if @expense.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

        <ul>
          <% @expense.errors.each do |error| %>
            <<li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.text_field :name, required: true, placeholder: "Expense name"  %>
    </div>

    <div class="field">
      <%= form.number_field :amount, required: true, placeholder: "Amount" %>
    </div>

    <div class="field">
      <%= form.label :categories %>
      <%= form.collection_select(:group_ids, current_user.groups, :id, :name, { selected: @group.id }, { multiple: true, class: "form-control" }) %>
    </div>

    <div class="actions">
      <%= form.submit "Save" %>
    </div>
  <% end %>

  <br>

  <%= link_to "", group_path(@group), class: 'back' %>
</section>

app/views/expenses/show.html.erb
<section class="single-expense">
<div class="nav">
<h5>Expense</h5>
</div>

<p style="color: green" class="notice"><%= notice %></p>

<%= render @expense %>

<%= link_to "",group_path(@group), class: 'back'%>

</section>